################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/crc.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/dcmi.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/dma2d.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/fmc.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/freertos.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/gpio.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/ltdc.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/main.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/quadspi.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/rtc.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/stm32h7xx_hal_msp.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/stm32h7xx_hal_timebase_tim.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/stm32h7xx_it.c \
../Application/User/Core/syscalls.c \
../Application/User/Core/sysmem.c \
D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/usart.c 

C_DEPS += \
./Application/User/Core/crc.d \
./Application/User/Core/dcmi.d \
./Application/User/Core/dma2d.d \
./Application/User/Core/fmc.d \
./Application/User/Core/freertos.d \
./Application/User/Core/gpio.d \
./Application/User/Core/ltdc.d \
./Application/User/Core/main.d \
./Application/User/Core/quadspi.d \
./Application/User/Core/rtc.d \
./Application/User/Core/stm32h7xx_hal_msp.d \
./Application/User/Core/stm32h7xx_hal_timebase_tim.d \
./Application/User/Core/stm32h7xx_it.d \
./Application/User/Core/syscalls.d \
./Application/User/Core/sysmem.d \
./Application/User/Core/usart.d 

OBJS += \
./Application/User/Core/crc.o \
./Application/User/Core/dcmi.o \
./Application/User/Core/dma2d.o \
./Application/User/Core/fmc.o \
./Application/User/Core/freertos.o \
./Application/User/Core/gpio.o \
./Application/User/Core/ltdc.o \
./Application/User/Core/main.o \
./Application/User/Core/quadspi.o \
./Application/User/Core/rtc.o \
./Application/User/Core/stm32h7xx_hal_msp.o \
./Application/User/Core/stm32h7xx_hal_timebase_tim.o \
./Application/User/Core/stm32h7xx_it.o \
./Application/User/Core/syscalls.o \
./Application/User/Core/sysmem.o \
./Application/User/Core/usart.o 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/crc.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/crc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/dcmi.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/dcmi.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/dma2d.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/dma2d.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/fmc.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/fmc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/freertos.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/freertos.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/gpio.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/gpio.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/ltdc.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/ltdc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/main.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/main.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/quadspi.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/quadspi.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/rtc.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/rtc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32h7xx_hal_msp.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/stm32h7xx_hal_msp.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32h7xx_hal_timebase_tim.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/stm32h7xx_hal_timebase_tim.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32h7xx_it.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/stm32h7xx_it.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/%.o Application/User/Core/%.su Application/User/Core/%.cyclo: ../Application/User/Core/%.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/usart.o: D:/APP/STM32CubeIDE_1.15.1/workspace/button/Core/Src/usart.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/STM32CubeIDE/Application/User/Hardware" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/include/gui/model" -I"D:/APP/STM32CubeIDE_1.15.1/workspace/button/TouchGFX/gui/common" -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Core

clean-Application-2f-User-2f-Core:
	-$(RM) ./Application/User/Core/crc.cyclo ./Application/User/Core/crc.d ./Application/User/Core/crc.o ./Application/User/Core/crc.su ./Application/User/Core/dcmi.cyclo ./Application/User/Core/dcmi.d ./Application/User/Core/dcmi.o ./Application/User/Core/dcmi.su ./Application/User/Core/dma2d.cyclo ./Application/User/Core/dma2d.d ./Application/User/Core/dma2d.o ./Application/User/Core/dma2d.su ./Application/User/Core/fmc.cyclo ./Application/User/Core/fmc.d ./Application/User/Core/fmc.o ./Application/User/Core/fmc.su ./Application/User/Core/freertos.cyclo ./Application/User/Core/freertos.d ./Application/User/Core/freertos.o ./Application/User/Core/freertos.su ./Application/User/Core/gpio.cyclo ./Application/User/Core/gpio.d ./Application/User/Core/gpio.o ./Application/User/Core/gpio.su ./Application/User/Core/ltdc.cyclo ./Application/User/Core/ltdc.d ./Application/User/Core/ltdc.o ./Application/User/Core/ltdc.su ./Application/User/Core/main.cyclo ./Application/User/Core/main.d ./Application/User/Core/main.o ./Application/User/Core/main.su ./Application/User/Core/quadspi.cyclo ./Application/User/Core/quadspi.d ./Application/User/Core/quadspi.o ./Application/User/Core/quadspi.su ./Application/User/Core/rtc.cyclo ./Application/User/Core/rtc.d ./Application/User/Core/rtc.o ./Application/User/Core/rtc.su ./Application/User/Core/stm32h7xx_hal_msp.cyclo ./Application/User/Core/stm32h7xx_hal_msp.d ./Application/User/Core/stm32h7xx_hal_msp.o ./Application/User/Core/stm32h7xx_hal_msp.su ./Application/User/Core/stm32h7xx_hal_timebase_tim.cyclo ./Application/User/Core/stm32h7xx_hal_timebase_tim.d ./Application/User/Core/stm32h7xx_hal_timebase_tim.o ./Application/User/Core/stm32h7xx_hal_timebase_tim.su ./Application/User/Core/stm32h7xx_it.cyclo ./Application/User/Core/stm32h7xx_it.d ./Application/User/Core/stm32h7xx_it.o ./Application/User/Core/stm32h7xx_it.su ./Application/User/Core/syscalls.cyclo ./Application/User/Core/syscalls.d ./Application/User/Core/syscalls.o ./Application/User/Core/syscalls.su ./Application/User/Core/sysmem.cyclo ./Application/User/Core/sysmem.d ./Application/User/Core/sysmem.o ./Application/User/Core/sysmem.su ./Application/User/Core/usart.cyclo ./Application/User/Core/usart.d ./Application/User/Core/usart.o ./Application/User/Core/usart.su

.PHONY: clean-Application-2f-User-2f-Core

